
all: data_process data_analysis

data_process: 
	gcc -o data_process data_process.c 
	./data_process

data_analysis: 
	gcc -o data_analysis data_analysis.c
	./data_analysis

clean:
	rm data_analysis data_process data_analysis.data data_process.data
